---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/


---
spring:
  profiles: sentence
server:
  port: 8082
words: noneWord

---
spring:
  profiles: subject
server:
  port: 0
words: I,You,He,She,It

---
spring:
  profiles: verb
server:
  port: 0
words: ran,knew,had,saw,bought

---
spring:
  profiles: noun
server:
  port: 0
words: boat,book,vote,seat,backpack,partition,groundhog,computer  
