---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka


---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog,computer  